language: node_js

sudo: false

cache: packages

node_js:
  - "0.10.38"

env:
  - CXX=g++-4.8 R_LIBS_USER=$HOME/R/Library

before_install:
  - npm install npm
  - npm install node-gyp
  - node-gyp rebuild --verbose

before_script:
  - echo $R_LIBS_USER
  - ls $R_LIBS_USER || mkdir -p $R_LIBS_USER
  - mkdir -p test-sync/js
  - mkdir -p test-sync/js-raw

script: 
  - npm test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
