language: node_js

node_js:
  - "0.10.38"

env:
  - CXX=g++-4.8

before_script:
  - Rscript -e "install.packages('jsonlite', repos = 'https://cloud.r-project.org')"

script: 
  - npm test
  - R CMD check --no-manual pkg

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - r-base