# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
hash_internal <- function(s, seed = 20160419L, size = 4194304L) {
    .Call('GmobiVectorizer_hash_internal', PACKAGE = 'GmobiVectorizer', s, seed, size)
}

